spring:
  main:
    web-application-type: none
  application:
    name: 12_spring_data_jpa_oneToMany
  datasource:
   url: jdbc:mysql://localhost:3306/test
   username: root
   password: srivatsan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    '[org.springframework.jdbc,org.springframework.data.jpa,org.hibernate.SQL]' : info
