spring:
  application:
    name: using-circuit-breaker
 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
resilience4j:
     circuitbreaker:
        instances:
          sample:
            registerHealthIndicator: true 
            automaticTransitionFromOpenToHalfOpenEnabled: true
            failureRateThreshold: 50
            minimumNumberOfCalls: 2
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 3
            waitDurationInOpenState: 5s
            slidingWindowType: COUNT_BASED

server:
  port: 9020

