spring:
  application:
    name: 10_spring_profile_runner
  config:
    activate:
      on-profile: dev

logging:
  level:
    '[org.springframework]': TRACE  	

server:
  port: 5050

com:
  example:
    demo:
      custom: custom property
---

spring:
 config:
    activate:
      on-profile : prod	

logging:
  level:
   '[org.springframework]': INFO    

server:
  port: 6060

com:
  example:
    demo:
     custom: custom property				