spring:
  application:
    name: microservice-one

server:
  port: 3030

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true	
    service-url:
     defaultZone: http://localhost:8761/eureka	

management:
    endpoints:
     web:
       exposure:
         include: "*"
